### ISSUE TITLE
Duplicate fields in the yaml file are not errored

### ISSUE THREAD

**Issue by MrKevinWeiss** [riot-appstore/memory_map_manager#47]
It seems that when there are two fields in the element section that have the same name it just overwrites...

```yaml
typedefs:
  sys_t:
    description: System settings for PHiLIP
    elements:
     - access: read-only
        description: The philip device designator - A constant number to identify philip firmware
        name: device_num
        type: uint32_t
        default: 17061
        description: The frequency of the system clock in Hz
        access: read-only
        name: sys_clk
        type: uint32_t
```
name just overwrites...  No error or anything.
